let managers=[],photoData='';const db=window.mwDb;const $=id=>document.getElementById(id);const clean=v=>String(v||'').trim();
$('loginBtn').onclick=()=>{if(clean($('loginId').value)!=='myeongwol'||clean($('loginPw').value)!=='mw2140!'){alert('아이디 또는 비밀번호가 틀렸습니다.');return}$('loginBox').hidden=true;$('adminWrap').hidden=false;load()};
function normalize(v){return Array.isArray(v)?v.filter(Boolean):v?Object.values(v):[]}
function load(){db.child('managers').on('value',s=>{managers=normalize(s.val());render()})}
function compress(file){return new Promise((ok,no)=>{const r=new FileReader;r.onerror=no;r.onload=e=>{const im=new Image;im.onerror=no;im.onload=()=>{const scale=Math.min(1,1000/im.width),c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);ok(c.toDataURL('image/jpeg',.76))};im.src=e.target.result};r.readAsDataURL(file)})}
$('photo').onchange=async e=>{const f=e.target.files[0];if(!f)return;$('preview').textContent='사진 처리 중...';try{photoData=await compress(f);$('preview').innerHTML=`<img src="${photoData}" alt="미리보기">`}catch{alert('사진을 처리하지 못했습니다.')}};
function clear(){['managerId','name','age','height','body','work','intro'].forEach(id=>$(id).value='');$('photo').value='';photoData='';$('preview').textContent='사진 미리보기'}
$('clearBtn').onclick=clear;
$('saveBtn').onclick=async()=>{const name=clean($('name').value);if(!name){alert('이름을 입력해주세요.');return}const id=clean($('managerId').value);const old=id?managers.find(m=>String(m.id)===id):null;const item={id:id||String(Date.now()),name,age:clean($('age').value),height:clean($('height').value),body:clean($('body').value),work:clean($('work').value),intro:clean($('intro').value),image:photoData||(old&&old.image)||''};if(id)managers[managers.findIndex(m=>String(m.id)===id)]=item;else managers.push(item);await save();clear();alert('프로필이 저장되었습니다.')};
async function save(){await db.child('managers').set(managers)}
function edit(id){const m=managers.find(x=>String(x.id)===String(id));if(!m)return;['name','age','height','body','work','intro'].forEach(k=>$(k).value=m[k]||'');$('managerId').value=m.id;photoData='';$('preview').innerHTML=m.image?`<img src="${m.image}" alt="미리보기">`:'사진 미리보기';scrollTo({top:0,behavior:'smooth'})}
async function del(id){if(!confirm('이 프로필을 삭제할까요?'))return;managers=managers.filter(x=>String(x.id)!==String(id));await save()}
async function move(id,d){const i=managers.findIndex(x=>String(x.id)===String(id)),n=i+d;if(i<0||n<0||n>=managers.length)return;[managers[i],managers[n]]=[managers[n],managers[i]];await save()}
function render(){$('count').textContent=managers.length+'명';$('managerList').innerHTML=managers.length?managers.map((m,i)=>`<article class="manager"><div>${m.image?`<img src="${m.image}" alt="">`:'사진 없음'}</div><div><strong>${m.name}</strong><span>${m.age||'나이 문의'} · ${m.height||'키 문의'} · ${m.work||'출근시간 문의'}</span></div><div><button onclick="move('${m.id}',-1)" ${i===0?'disabled':''}>▲</button><button onclick="move('${m.id}',1)" ${i===managers.length-1?'disabled':''}>▼</button><button onclick="edit('${m.id}')">수정</button><button class="delete" onclick="del('${m.id}')">삭제</button></div></article>`).join(''):'<p>등록된 프로필이 없습니다.</p>'}
window.edit=edit;window.del=del;window.move=move;
